<<<<<<< HEAD
wcs_coav_flight:
    resource: "@WCSCoavBundle/Controller/FlightController.php"
    type:     annotation

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Controller/ReservationController.php"
    type:     annotation

wcs_coav_plane_model:
    resource: "@WCSCoavBundle/Controller/PlaneModelController.php"
    type:     annotation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /

=======
>>>>>>> e87948ce09d67d47f1bab433cf8c2dd37349bc17
app:
    resource: '@AppBundle/Controller/'
    type: annotation
